name: Create Docker image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        
      - name: Generate image
        run: docker build -t ${{ secrets.DOCKER_SOURCE }}/${{ secrets.DOCKER_USERNAME }}/crm.identity/crm.identity:latest --build-arg NUGET_SOURCE=${{ secrets.NUGET_SOURCE }} --build-arg NUGET_USERNAME=${{ secrets.NUGET_USERNAME }} --build-arg NUGET_PASSWORD=${{ secrets.NUGET_PASSWORD }} .
        
      - name: Login to registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} ${{ secrets.DOCKER_SOURCE }}
      
      - name: Push image
        run: docker push ${{ secrets.DOCKER_SOURCE }}/${{ secrets.DOCKER_USERNAME }}/crm.identity/crm.identity:latest
